### ISSUE TITLE
Environment Variable

### ISSUE THREAD

**Issue by sganeshkanna** [google-pay/gpay-loyaltyapi-demo#3]
I followed the steps one by one and when i run the serve.sh i am getting GCP_Credentials not found though I can able to print the $GCP_CREDENTIALS
Please suggest me wht to do.

**Comment by media599** [comment]
Same issue here, in shell online and locally both same issue, while i added it to the env file and i exported it.

**Comment by JlUgia** [comment]
Hi, we recommend you to take a look at [the new codelab for Web](https://github.com/google-pay/wallet-web-codelab). In this workshop we are concentrating only of the key steps of the integration so that you can seamlessly integrate in solving for your use case.

Let me know if you are able to progress.
